apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/deployment.yaml
- ../../base/service.yaml
namePrefix: prod-
namespace: prod
patchesStrategicMerge:
- resourceconstraints_patch.yaml
- environment_patch.yaml
- healthcheck_patch.yaml
- increase_replicas_patch.yaml