apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/deployment.yaml
- ../../base/service.yaml
namePrefix: prod-
commonLabels:
  env: prod
namespace: prod
patchesStrategicMerge:
- resource_constraints_patch.yaml
- environment_patch.yaml
- health_check_patch.yaml
- increase_replicas_patch.yaml