server:
  shutdown: graceful
spring:
  application:
    name: kustomize-demo
  lifecycle:
    timeout-per-shutdown-phase: 20s
  main:
    cloud-platform: kubernetes

  # https://docs.spring.io/spring-cloud-kubernetes/docs/1.1.6.RELEASE/reference/html/#propertysource-reload
  cloud.kubernetes.reload:
    enabled: true
    strategy: restart_context

management:
  # needed for the PropertySource Reload feature of Spring Cloud Kubernetes
  endpoint:
    restart:
      enabled: true

  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.cloud: debug
