server:
  shutdown: graceful
spring:
  application:
    name: kustomize-demo
  lifecycle:
    timeout-per-shutdown-phase: 20s
  main:
    cloud-platform: kubernetes

  cloud.kubernetes.secrets:
    name: kustomize-demo
    namespace: dev

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.cloud: debug
