server:
  shutdown: graceful
spring:
  application:
    name: kustomize-demo
  lifecycle:
    timeout-per-shutdown-phase: 20s
  main:
    cloud-platform: kubernetes

management:
  endpoints:
    web:
      exposure:
        include: '*'
