apiVersion: v1
kind: Service
metadata:
  labels:
    app: kustomize-demo
  name: kustomize-demo
spec:
  selector:
    app: kustomize-demo
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP