apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kustomize-demo-deployment
  name: kustomize-demo-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kustomize-demo-deployment
  template:
    metadata:
      labels:
        app: kustomize-demo-deployment
    spec:
      containers:
        - image: kustomize-demo:0.0.1-SNAPSHOT
          name: kustomize-demo
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: db.username
                  name: kustomize-demo-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db.password
                  name: kustomize-demo-secret
---
apiVersion: v1
kind: ConfigMap
data:
  greeter.message: Hello from prod namespace
metadata:
  name: kustomize-demo
  namespace: prod

---
apiVersion: v1
kind: Secret
type: Opaque
data:
  db.username: YWRtaW4=
  db.password: TUhYY3R6QmV3SmFwekNUVFR2SERZTjJ6
metadata:
  name: kustomize-demo-secret
  namespace: prod