apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kustomize-demo-deployment
  name: kustomize-demo-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kustomize-demo-deployment
  template:
    metadata:
      labels:
        app: kustomize-demo-deployment
    spec:
      containers:
        - image: kustomize-demo:0.0.1-SNAPSHOT
          name: kustomize-demo
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: GREETER_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: kustomize-demo-configmap
                  key: greeter.message
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kustomize-demo-secret
                  key: db.username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kustomize-demo-secret
                  key: db.password
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: ConfigMap
data:
  greeter.message: Hello from dev namespace
metadata:
  name: kustomize-demo-configmap
  namespace: dev

---
apiVersion: v1
kind: Secret
type: Opaque
data:
  db.username: YWRtaW4=
  db.password: dmVyeXNlY3JldAo=
metadata:
  name: kustomize-demo-secret
  namespace: dev

