apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kustomize-demo-deployment
  name: kustomize-demo-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kustomize-demo-deployment
  template:
    metadata:
      labels:
        app: kustomize-demo-deployment
    spec:
      containers:
        - image: kustomize-demo:0.0.1-SNAPSHOT
          name: kustomize-demo
          volumeMounts:
            - name: kustomize-demo-secret-volume
              mountPath: /var/kustomize-demo
      volumes:
        - name: kustomize-demo-secret-volume
          secret:
            secretName: kustomize-demo-secret

---
apiVersion: v1
kind: ConfigMap
data:
  greeter.message: Hello from dev namespace
metadata:
  name: kustomize-demo
  namespace: dev

---
apiVersion: v1
kind: Secret
type: Opaque
data:
  db.username: YWRtaW4K
  db.password: dmVyeXNlY3JldAo=
metadata:
  name: kustomize-demo-secret
  namespace: dev

