apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-demo
spec:
  template:
    spec:
      containers:
        - name: kustomize-demo
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev