apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/deployment.yaml
- ../../base/service.yaml
namespace: dev
patchesStrategicMerge:
  - environment_patch.yaml
#- healthcheck_patch.yaml